/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kuota.program;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class LoginKuota extends javax.swing.JFrame {
    Connection conn = null;
    Statement st = null;

    public LoginKuota() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public LoginKuota(java.awt.Frame parent, boolean modal) {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/kuota","root","");
            st = conn.createStatement();
        }
        catch(Exception ex){
        JOptionPane.showMessageDialog(null,"Gagal Terkoneksi Karena " + ex);
        }
    }

    private void CekLogin(){
        try{
            if(txtno_telp.getText().equals("") && txtnik.getText().equals("")){
                JOptionPane.showMessageDialog(rootPane, "Data Tidak Boleh Kosong!", "Pesan", JOptionPane.ERROR_MESSAGE);
                txtno_telp.requestFocus();
                hapuslayar();
            }
            else if (txtno_telp.getText().equals("")){
                JOptionPane.showMessageDialog(rootPane, "No Hp Tidak Boleh Kosong!");
                txtno_telp.requestFocus();
            }
            else if (txtnik.getText().equals("")){
                JOptionPane.showMessageDialog(rootPane, "NIK Tidak Boleh Kosong!");
                txtnik.requestFocus();
            }
            else{
                st = conn.createStatement();
                String sql = ("SELECT * FROM customer WHERE no_telp ='"+txtno_telp.getText()+"' AND nik ='"+String.valueOf(txtnik.getText())+"'");
                ResultSet rs = st.executeQuery(sql);
            
                if(rs.next()){
                    this.dispose();
                    new MenuUtama().setVisible(true); 
                }
                else{
                    JOptionPane.showMessageDialog(rootPane, "No Hp atau NIK Anda Salah, atau Akun Belum Terdaftar, Silahkan Registrasi", "Pesan",
                    JOptionPane.ERROR_MESSAGE);
                    hapuslayar();
                }
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    private void hapuslayar(){
        txtno_telp.setText("");
        txtnik.setText("");
        txtno_telp.setEnabled(true);
        txtnik.setEnabled(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtno_telp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtnik = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnRegistrasi1 = new javax.swing.JLabel();
        exitLogin = new javax.swing.JLabel();
        miniLogin = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(375, 500));

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kuota/program/icon/back2.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 140, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("No Hp");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, 30));

        txtno_telp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtno_telpActionPerformed(evt);
            }
        });
        jPanel1.add(txtno_telp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 180, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NIK");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 42, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 8)); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txtnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnikActionPerformed(evt);
            }
        });
        jPanel1.add(txtnik, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 180, 30));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Belum Punya Akun?");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 110, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kuota/program/icon/icon.png"))); // NOI18N
        jLabel4.setText(" ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, 150));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/kuota/program/icon/back1.png"))); // NOI18N
        jLabel5.setText(" ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 70, -1));

        btnRegistrasi1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnRegistrasi1.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrasi1.setText("Registrasi");
        btnRegistrasi1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrasi1MouseClicked(evt);
            }
        });
        jPanel1.add(btnRegistrasi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 80, 50));

        exitLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exitLogin.setForeground(new java.awt.Color(255, 255, 255));
        exitLogin.setText("X");
        exitLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLoginMouseClicked(evt);
            }
        });
        jPanel1.add(exitLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 16, -1, -1));

        miniLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        miniLogin.setForeground(new java.awt.Color(255, 255, 255));
        miniLogin.setText("-");
        miniLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miniLoginMouseClicked(evt);
            }
        });
        jPanel1.add(miniLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 12, 20, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Login");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 90, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtno_telpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtno_telpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtno_telpActionPerformed

    private void txtnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnikActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        CekLogin();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnRegistrasi1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrasi1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new FormRegistrasi().setVisible(true);
        /*this.setVisible(false);
        new FormRegistrasi().setVisible(true);
        */
       
    }//GEN-LAST:event_btnRegistrasi1MouseClicked

    private void exitLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLoginMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitLoginMouseClicked

    private void miniLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniLoginMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_miniLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginKuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginKuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginKuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginKuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoginKuota dialog = new LoginKuota(new javax.swing.JFrame(),
            true);
                dialog.addWindowListener(new
                java.awt.event.WindowAdapter() {
                @Override
            public void

            windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
            }
                });
            dialog.setVisible(true);
            }
                });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel btnRegistrasi1;
    private javax.swing.JLabel exitLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel miniLogin;
    private javax.swing.JTextField txtnik;
    private javax.swing.JTextField txtno_telp;
    // End of variables declaration//GEN-END:variables
}
